[
    "Airbus A321",
    "Airbus A350-900",
    "Boeing 737-800 (winglets)",
    "Boeing 787-9",
    "BCS3",
    "Airbus A320 (sharklets)",
    "Boeing 737 MAX 8",
    "Airbus A380-800",
    "Airbus A319",
    "Airbus A330-300",
    "Boeing 737-800"
]